### ISSUE TITLE
build issue on zig 0.14.0-dev.2034+56996a280

### ISSUE THREAD

**Issue by fr13ndxd** [DerryAlex/zig-gir-ffi#33]
getting this error when i build on zig 0.14.0-dev.2034+56996a280:
```zig
[fr13nd@nixos:~/Desktop/zig/gtk4-test]$ zig build
install
└─ install status-bar
   └─ zig build-exe status-bar Debug native 1 errors
/home/fr13nd/.cache/zig/p/1220ee3e898557547c4096198a4451c264f1af01f34143344e0e8794c4d8da815b2e/glib.zig:2370:5: error: duplicate struct member name 'destroy'
    destroy: ?*const fn (_data: ?*anyopaque) callconv(.C) void,
    ^~~~~~~
/home/fr13nd/.cache/zig/p/1220ee3e898557547c4096198a4451c264f1af01f34143344e0e8794c4d8da815b2e/glib.zig:2378:12: note: duplicate name here
    pub fn destroy(_hook_list: *glib.HookList, _hook_id: u64) bool {
           ^~~~~~~
/home/fr13nd/.cache/zig/p/1220ee3e898557547c4096198a4451c264f1af01f34143344e0e8794c4d8da815b2e/glib.zig:2362:25: note: struct declared here
pub const Hook = extern struct {
                 ~~~~~~~^~~~~~
```
 (pls help)
 
 edit: using https://github.com/DerryAlex/zig-gir-ffi/releases/download/0.10.2/gtk4.tar.gz

**Comment by DerryAlex** [comment]
0.10.2 is for zig 0.13.0. Try master branch or use an older version of zig or simply rename one of them (e.g. `fn destroy` -> `fn destroyID`).

I just updated CI so that it would be possible to download artifacts for master in the future if 'invalid magic header' for typelib is resolved.
[gtk4.tar.gz](https://github.com/user-attachments/files/17606339/gtk4.tar.gz)
